#Yucca configuration
yucca:
    #DB connections
    connections:
        default:
            type: doctrine
            options:
                driver:   %database_default_driver%
                host:     %database_default_host%
                port:     %database_default_port%
                dbname:   %database_default_name%
                user:     %database_default_user%
                password: %database_default_password%
                charset:  UTF8
        order1:
            type: doctrine
            options:
                driver:   %database_order1_driver%
                host:     %database_order1_host%
                port:     %database_order1_port%
                dbname:   %database_order1_name%
                user:     %database_order1_user%
                password: %database_order1_password%
                charset:  UTF8
        order2:
            type: doctrine
            options:
                driver:   %database_order2_driver%
                host:     %database_order2_host%
                port:     %database_order2_port%
                dbname:   %database_order2_name%
                user:     %database_order2_user%
                password: %database_order2_password%
                charset:  UTF8


    #DB Schema
    schema:
        user:
            sharding_strategy: modulo
            shards:
                - default

        order:
            sharding_strategy: modulo
            shards:
                - order1
                - order1
                - order1
                - order1
                - order1
                - order2
                - order2
                - order2
                - order2
                - order2

    #Sources
    sources:
        user:
            default_params:
                fields: { id: {type: 'identifier'}, email: ~, last_name: ~, first_name: ~}
            handlers:
                -
                    type: database_single_row
                    table_name: user

        order:
            default_params:
                fields: { id: {type: 'identifier'}, amount: ~, user_id: {type:'object', class_name:'Acme\Bundle\YuccaDemoBundle\Entity\User'}, created_at: {type: 'datetime'}, sharding_key: ~ }
            handlers:
                -
                    type: database_single_row
                    table_name: order



    #Sources
    mapping:
        #
        # CarBundle
        #
        Acme\Bundle\YuccaDemoBundle\Entity\User:
            mapper_class_name: ~
            properties:
                lastName:
                    field: last_name
                firstName:
                    field: first_name
            sources:
                - user
        Acme\Bundle\YuccaDemoBundle\Entity\Order:
            mapper_class_name: ~
            properties:
                createdAt:
                    field: created_at
                user:
                    field: user_id
            sources:
                - order

    #Selectors
    selectors:
        Acme\Bundle\YuccaDemoBundle\Selector\User:
            sources:
                - database
        Acme\Bundle\YuccaDemoBundle\Selector\Order:
            sources:
                - database
